---
# tasks file for donfilemon.grafana
- name: download Graphana DEB file
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ graphana_version }}_amd64.deb "
    dest: /tmp/grafana_{{ graphana_version }}_amd64.deb
  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
- name: download Graphana RPM file
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ graphana_version }}.x86_64.rpm "
    dest: /tmp/grafana_{{ graphana_version }}.x86_64.rpm 
  when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "RedHat")   
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - adduser
    - libfontconfig
  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
- name: Install a list of packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - adduser
    - libfontconfig
  when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "RedHat")
- name: Install a graphana.deb package
  apt:
    deb: /tmp/grafana_{{ graphana_version }}_amd64.deb
  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
- name: Install a graphana.rpm package
  yum:
    name: /tmp/grafana_{{ graphana_version }}.x86_64.rpm
  when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "RedHat")
- name: just force systemd to reread configs (only ansible 2.4 and above)
  systemd: daemon_reload=yes
- name: stop service cron on debian, if running
  systemd: name=grafana-server state=started
