- name: Depoly robertfil.pl
  hosts: test
  become: true
  gather_facts: yes
  tasks:
    - name: Install Java Open-JDK
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
  roles:
    #- letsencrypt
    - ansible-role-certbot-master
    - nginx
    
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_hour: 3
    certbot_auto_renew_minute: 30
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_create_standalone_stop_services:
      - nginx
    certbot_admin_email: kontakt@robertfil.pl
    certbot_install_from_source: true
    certbot_repo: https://github.com/certbot/certbot.git
    certbot_version: master
    certbot_keep_updated: true
    certbot_certs:
      - email: janedoe@example.com
        domains:
          - robertfil.pl
  
    