#letsencrypt/tasks/main.yml

#- name: Install depends
  #yum:
  #  name: "{{ packages }}"
  #vars:
  #  packages:
  #    - python
      #- python-dev
    #   - dialog
     # - libaugeas0
      #- augeas-lenses
      #-# libssl-dev
      #- libffi-dev
      #- ca-certificates
      #- python-pip
      #- python-virtualenv
      #- git
      #- libpython-dev
      #- zlib1g-dev
- name: Lets Encrypt client
  git: dest=/opt/certbot clone=yes repo=https://github.com/certbot/certbot force=yes
# Auto-renew certificates and reload nginx
- name: Add crontab to renew certificates
  cron: minute="30" hour="2" weekday="1" job="/opt/certbot/certbot-auto renew >> /var/log/le-renew.log"
- name: Add crontab to reload server
  cron: minute="35" hour="2" weekday="1" job="/etc/init.d/nginx reload"
